

POST http://localhost:1337/user/register
Content-Type: application/json

{
    "uname":"rakesh",
    "fname":"soumyadip",
    "email":"test2@email.com",
    "pword":"123456789"

}
###

GET http://localhost:1337/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJha2VzaCIsImVtYWlsIjoidGVzdDJAZW1haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkWEFUbzMuM0c5VVloRXhOand4Qk5QTzVkUXpRUThUai43WnZycTlTY0NYZVpjMXdkNWM3TS4iLCJpYXQiOjE2NTgxNTE1OTR9.x9U2JvlkbGuOxDCMdFgGXCMMkSWpciWlfk57VEFph1g

###
POST http://localhost:1337/user/login
Content-Type: application/json

{
    "name":"rakesh",
    "password":"12345678"
}

###
GET http://localhost:1337/acc/get/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvbG8iLCJlbWFpbCI6InRlc3QyQGVtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGZCVm0wNVByTnJtWkJhRXFaNEU5V3VqZG1abGJSSjlHcXdjU05HOFRobDdaWFBVSHhld2NLIiwiaWF0IjoxNjU4MTQxMTYzfQ.A3rf9Kb5Xde93X20yAg--LXOaZMCXhHr6H7U6J8SjHA
